1_start
Elraden/nest_booking pull request #1
Opened 2024-12-20 13:04 UTC by Elraden

2024-12-23 19:38 UTC, alex13slem requested changes

2024-12-23 19:38 UTC, alex13slem commented on src/configs/mongo.config.ts
> +		uri: `mongodb://${configService.get<string>('MONGO_LOGIN')}:${configService.get<string>('MONGO_PASSWORD')}@${configService.get<string>('MONGO_HOST')}:${configService.get<string>('MONGO_PORT')}/${co
Через конкатенацию строк смотрелось бы понятнее)

2024-12-23 19:38 UTC, alex13slem commented on src/room/room.controller.ts
> +		return this.roomService.findById(id);
Нет обработки исключений типа NotFound

2024-12-24 06:39 UTC, Elraden commented on src/room/room.controller.ts
> +		return this.roomService.findById(id);
Добавил, текст ошибки вынес в константы

2024-12-24 06:39 UTC, Elraden commented on src/configs/mongo.config.ts
> +		uri: `mongodb://${configService.get<string>('MONGO_LOGIN')}:${configService.get<string>('MONGO_PASSWORD')}@${configService.get<string>('MONGO_HOST')}:${configService.get<string>('MONGO_PORT')}/${co
Вынес получение данных из env в переменные, оставил интерполяцию, но теперь она более читаема.

2025-01-07 14:33 UTC, alex13slem approved these changes

2025-01-07 16:01 UTC, merged